const express = require('express');
const cors = require('cors');
const mongoose = require('mongoose');
const path = require('path'); // IMPORTANT: Added to resolve folder paths
require('dotenv').config();

const app = express();

// Middleware
app.use(cors());
app.use(express.json());

// Import Routes
const authRoutes = require('./routes/auth');
const heritageRoutes = require('./routes/heritage'); 

// API Routes (These must remain ABOVE the frontend code)
app.use('/api/auth', authRoutes);
app.use('/api/heritage', heritageRoutes); 

// Connect to MongoDB
mongoose.connect(process.env.MONGO_URI, {
  family: 4 // This strictly forces Node.js to use IPv4
})
  .then(() => console.log('Successfully connected to the MongoDB filing cabinet!'))
  .catch((err) => console.log('Database connection error:', err));

// --- SERVE FRONTEND STATIC FILES ---
// 1. Tell Express to serve the static files generated by Vite/React
app.use(express.static(path.join(__dirname, '../frontend/dist')));

// 2. Catch-all route: If the request isn't an API route, send back the React index.html
// This is essential so React Router (like your /explore or /login pages) works without throwing a 404 error
app.get('/{*any}', (req, res) => {
  res.sendFile(path.join(__dirname, '../frontend/dist/index.html'));
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});